### ISSUE TITLE
Rebuilding with changed asset

### ISSUE THREAD

**Issue by rikk811** [greg-ynx/NexusDownloadFlow#17]
First, thank you for this auto-clicker!... I suck with Python. 
I am trying to use this with downloading collections from Nexus. It's currently not seeing the 'download' button on NMM. Looking at the assets, I see that it isn't there. I took a screen snip of the image and placed it in the asset folder. However, I'm not sure how to rebuild and run the files with the edit. Please help!

**Comment by greg-ynx** [comment]
Hi! If you cannot build NDF just run it with python and it will work!

Make sure that your screenshot is named template1.png or template2.png or template3.png (current version 2.0.1) does not support additional template.

If you really want to build the python project into a window executable, you have to use pyinstaller with the build.spec file. Or if you have download all the dependencies on your global python interpreter, just click the build.bat file.

Hope this will help 😉

**Comment by greg-ynx** [comment]
New version released! [2.1.0](https://github.com/greg-ynx/NexusDownloadFlow/releases/tag/v2.1.0)

Adding custom templates is a feature in this version. I'm closing this issue.
