### ISSUE TITLE
Program not recognizing download button in Wabbajack

### ISSUE THREAD

**Issue by ethanwdp** [greg-ynx/NexusDownloadFlow#18]
Platform: Wabbajack 3.5.0.1
NexusDownloadFlow version: 2.0.1
Operating System (OS) and its architecture (32bits, 64bits): Windows 10 x64
System RAM capacity: 32GB DDR4
Monitors: 2; 2560x1440 - 1600x900
Issue description:

Hello, I am having an issue where the program does not recognize the Nexus download button. There is nothing in the log so I hope an image will suffice. I'm assuming this is a template issue, but the templates provided look identical to the button and there does not appear to be any documentation on how to format a custom template.

![issue](https://github.com/greg-ynx/NexusDownloadFlow/assets/10551622/70a18ae4-cbca-48c1-9b58-8bb094201d15)

**Comment by greg-ynx** [comment]
Hi sorry for my late answer...

Have you tried to maximize the Nexus mods page on each of your monitors?

I'm about to add back the option to add custom templates samples in next versions of NDF.

Use the first released version if you want to use your own templates for now

Hope this will help 😅

**Comment by greg-ynx** [comment]
New version released! [2.1.0](https://github.com/greg-ynx/NexusDownloadFlow/releases/tag/v2.1.0)

**Comment by greg-ynx** [comment]
Adding custom template is now a feature of NDF. I will close this issue for now.
