### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by Brokenspace666** [greg-ynx/NexusDownloadFlow#27]
This isn't much of an issue its more of a suggestion but is it possible this could be updated to work with the nolvus launcher is it currently doesn't

**Comment by greg-ynx** [comment]
Hi! I'm currently working on 2.1.0 version where you can add and use you own set of templates. With this feature you will be able to use NDF with Nolvus launcher 🙂

**Comment by Brokenspace666** [comment]
> Hi! I'm currently working on 2.1.0 version where you can add and use you own set of templates. With this feature you will be able to use NDF with Nolvus launcher 🙂

You are just amazing

**Comment by greg-ynx** [comment]
New version released! [2.1.0](https://github.com/greg-ynx/NexusDownloadFlow/releases/tag/v2.1.0)

Tell me if NDF works with Nolvus now 😄
