### ISSUE TITLE
Updated version of this program

### ISSUE THREAD

**Issue by Aareon** [greg-ynx/NexusDownloadFlow#3]
Hi! I loved your program so much that I forked and updated it. You can find it [here](https://github.com/Aareon/NexusDownloadFlow-2023). I wasn't sure how you were creating your binary/installer so I slapped something together. No installer necessary, just download and run. Offers a configurable option for how long to wait between screenshots. Hope you enjoy!

**Comment by greg-ynx** [comment]
Hi @Aareon , glad to see that you loved this program!

Following the latest open issues for NDF-2022, I actually wanted to create a new version of this program. I'd like to talk with you about your release approach. 

I had found a more efficient algorithm for image recognition with OpenCV at the time, and I'd like to implement it in a new version too. So I'm going to relaunch the development of NexusDownloadFlow to make the program will be more accessible to the community and iron out any bugs encountered.

I haven't yet been able to test your version of this program, but I'll be sure to take a look at it when I get the chance.

I look forward to working with you on future versions 😃

**Comment by Aareon** [comment]
@greg-ynx I'd be happy to work with you. I also have an interest in developing a UI for the program. I will merge any improvements you decide to make upstream into the 2023 repo, and will be adding my own UI as well. I hope we can come together to accomplish this ♥️

**Comment by Aareon** [comment]
I'm very interested to see your better method for template matching

**Comment by greg-ynx** [comment]
Hi! I don't remember the name of the algorithm but I will search for it when I have the time 😉

**Comment by greg-ynx** [comment]
Hi @Aareon ! I've just released the 2.0.0 version of NDF hope that you could make it a better program with its new algorithm. I've seen that someone fork your repository in order to add image recognition for Vortex' download button. I think that could be a great minor update for v2.1.0.

Anyway I am available if you want to discuss about this update. I will close the issue for now on.

See you later! 😉
